### ISSUE TITLE
Cool lib!

### ISSUE THREAD

**Issue by evshvarov** [d-little/integ2json#3]
Hi @d-little !

Do you want to share your app on [Open Exchange](https://openexchange.intersystems.com/)?
This [takes 5 min](https://www.youtube.com/watch?v=duAVaIEeXS8&t=9s) but makes your repo much more noticed. Thanks!

**Comment by d-little** [comment]
Hey @evshvarov, thanks!  I'm in the slow process of re-writing a few pieces of this.  Same functionality, just a little 'cleaner'.  I'm obviously not a developer, just someone who wants this as a tool so I'm learning as I go ;)

I'll let you know when a newer version is done, and will look at posting it on Open Exchange.

Cheers!

**Comment by evshvarov** [comment]
Got you!
Looking forward!
Evgeny
